services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cat_feed
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data